task1: task1.c
	gcc -o task1 task1.c -ggdb -g3 -Wall -Wextra

task2: task2.c
	gcc -o task2 task2.c -ggdb -g3 -Wall -Wextra -no-pie

task3: task3.c
	gcc -o task3 task3.c -ggdb -g3 -Wall -Wextra -O3 -no-pie
